function pacemaker = LRCread_pacemaker(fileID)
%LRCREAD_PACEMAKER Replace with native C functions
%   For use with MATLAB only. DO NOT use for codegen.
%   Does NOT support commas within strings.

formatSpec = '%f %f %s %s %f %f %f %f %f %f %f %*[^\n]';
C = {};
while ~feof(fileID)
    D = textscan(fileID,formatSpec,inf,...
        'Delimiter',',','HeaderLines',1,'TreatAsEmpty','null');
    C = [C;D];
end

if size(C,1) > 1
    % Find empty cells
    idxEmpty = cellfun(@isempty,C);
    % Find empty rows
    rowEmpty = all(idxEmpty,2);
    % Delete empty rows
    C(rowEmpty,:) = [];
end

pacemaker = struct(         ...
    'runTimeUTC',	C(1),	...
    'runTimeOffset',C(2),	...
    'version',      C(3),	...
    'model',        C(4),	...
    'x0',           C(5),	...
    'xc0',          C(6),	...
    't0',           C(7),	...
    'xn',           C(8),	...
    'xcn',          C(9),	...
    'tn',           C(10),	...
    'targetPhase',  C(11)   ...
    );

end

